### ISSUE TITLE
Bit Vectors and most vs least significant bit

### ISSUE THREAD

**Issue by merijn** [Bodigrim/bitvec#1]
I really like the current unboxed implementation of bit vectors and how it plays nicely with other libraries based on vector, but I think there are some additions that'd be nice to have.

I've been using bit vectors for dealing with incremental construction of network packets (together with vector-sized), which works really well for constructing things, but converting to/from these bit vectors to `ByteString` is rather annoying. As most networking protocols are specified with bit 0 = most significant bit, as opposed to bit 0 = least significant bit.

To simplify my life I'm currently writing some newtype wrappers that use different indexing logic to extract bits so I can more conveniently go from `ByteString`/`Storable.Vector Word8` to a bit vector with the data I expect. I think it'd be nice to add these newtypes and conversion code to `bitvec` when I'm done.

So consider this issue a poll whether there's interest to merge this functionality and a bikeshedding opportunity on naming of any of this code and how to integrate it with the existing code.

I was thinking of maybe defining another newtype for `Bit` that has a type parameter that indicates the bit addressing (so whether 0 is least/most significant), additionally I think it'd be nice to have some more functions for creating bit vectors from other vectors, rather than only from `Vector Word`.

**Comment by Bodigrim** [comment]
I definitely welcome more conversions to/from various vectors. BTW I am unhappy with current 
```haskell
fromWords :: Int -> Vector Word -> Vector Bit
```
and rather have more primitive `fromWords :: Vector Word -> Vector Bit`. User can always slice a vector afterwards.

**Comment by Bodigrim** [comment]
It seems totally reasonable to support MSB as well, but I am not sure about best way to expose it. Adding a type parameter to `Bit` seems to be quite a breaking change and may bring too much confusion to some users, because in many applications endianness does not matter.

Actually, is it a property of `Bit`? Isn't it enough to apply `V.map reverseBits :: Vector Word -> Vector Word`, provided an efficient implementation for `reverseBits :: Word -> Word`? (Sorry, if I am talking nonsense)

**Comment by merijn** [comment]
I didn't necessarily mean modifying the current `Bit` newtype, as that probably leads to too much backwards incompatible churn, I was thinking more along the lines of adding a new newtype that wrap `Bit` with a phantom parameter, but I'm not entirely convinced.

> Isn't it enough to apply V.map reverseBits :: Vector Word -> Vector Word, provided an efficient implementation for reverseBits :: Word -> Word? (Sorry, if I am talking nonsense)

I'd have to think about it/play with things to check. Honestly, I'm currently dealing with both the distinction of 0 is most vs least significant, as well as parts of my data being network byte ordering, which makes things...confusing.

I'm basically using different vector types as read-only views to raw data, so I find myself often wanting to convert to/from Vector Word16, Vector Word32, and Vector Bit. The `V.map reverseBits :: Vector Word -> Vector Word` approach is certainly doable for one-of interactions, but I think for larger amounts of data it'd be nice to have a more principled approach providing a read-only view.

**Comment by Bodigrim** [comment]
I've been thinking about this problem and whipped up https://github.com/Bodigrim/rotcev to provide a wrapper for an arbitrary `Vector` with O(1) `reverse`. Instead of creating a copy, this wrapper just flips a flag, which inverts indexation. This is the same idea as O(1) slicing.

Do you think it might be useful?

**Comment by Bodigrim** [comment]
Closing, because I think that https://github.com/Bodigrim/rotcev covers your use case, but feel free to reopen if you get other ideas to discuss.
